name: BroodmotherWebs
version: 1.0
main: com.udd108.broodmotherwebs.BroodmotherWebs
api-version: '1.21'
commands:
  bmwebs:
    description: Control layout mapping for Broodmother webs.
    permission: broodmotherwebs.admin
    usage: /bmwebs [scan]
